INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Constancia Cumplimiento SPD',
'{
  "VAR_FOLIO_CONSTANCIA": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_ASIGNATURA_ASESORIA": "",
  "VAR_PERIODO_CONSTANCIA": "",
  "VAR_TOTAL_ESTUDIANTES": "",
  "VAR_DIA_CONSTANCIA": "",
  "VAR_MES_CONSTANCIA": "",
  "VAR_ANIO_CONSTANCIA": "",
  "VAR_JEFE_CIENCIAS_BASICAS": "",
  "VAR_JEFE_SUBDIRECCION_ACADEMICA": "",
  "VAR_FIRMA_CIENCIAS_BASICAS": "",
  "VAR_FIRMA_SUBDIRECCION_ACADEMICA": ""
}');
INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Constancia DDIE (Competencias de Tutores)',
'{
  "VAR_FOLIO_CONSTANCIA": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_DURACION_HRS": "",
  "VAR_PERIODO": "",
  "VAR_DIA": "",
  "VAR_MES": "",
  "VAR_ANIO": "",
  "VAR_JEFE_DOCENCIA_E_INNOVACION_EDUCATIVA": "",
  "VAR_FIRMA_DOCENCIA_E_INNOVACION_EDUCATIVA": ""
}');
INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Oficio Comisión (Proyecto Estratégico)',
'{
  "VAR_OFICIO_COMISION": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_NOMBRE_CURSO": "",
  "VAR_FECHA_INICIO_COMISION": "",
  "VAR_FECHA_FIN_COMISION": "",
  "VAR_JEFE_DEPARTAMENTO_ACADEMICO": "",
  "VAR_FIRMA_DEPARTAMENTO_ACADEMICO": ""
}');

INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Oficio Comisión (Ambientes Virtuales)',
'{
  "VAR_OFICIO_COMISION": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_NOMBRE_CURSO": "",
  "VAR_FECHA_INICIO_COMISION": "",
  "VAR_FECHA_FIN_COMISION": "",
  "VAR_JEFE_DEPARTAMENTO_ACADEMICO": "",
  "VAR_FIRMA_DEPARTAMENTO_ACADEMICO": ""
}');

INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Oficio Comisión (curso_diplomado)',
'{
  "VAR_OFICIO_COMISION": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_NOMBRE_CURSO": "",
  "VAR_INSTITUCION_CURSO": "",
  "VAR_FECHA_INICIO_COMISION": "",
  "VAR_FECHA_FIN_COMISION": "",
  "VAR_JEFE_DEPARTAMENTO_ACADEMICO": "",
  "VAR_FIRMA_DEPARTAMENTO_ACADEMICO": ""
}');

INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Oficio Comisión (curso-diplomado DDIE)',
'{
  "VAR_OFICIO_COMISION": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_NOMBRE_CURSO": "",
  "VAR_FECHA_INICIO_COMISION": "",
  "VAR_FECHA_FIN_COMISION": "",
  "VAR_JEFE_DEPARTAMENTO_ACADEMICO": "",
  "VAR_FIRMA_DEPARTAMENTO_ACADEMICO": ""
}');

INSERT INTO DOCUMENTO(NOMBRE, DATOS_JSON) VALUES ('Oficio Comisión (Educación Inclusiva)',
'{
  "VAR_OFICIO_COMISION": "",
  "VAR_NOMBRE_DOCENTE": "",
  "VAR_NOMBRE_CURSO": "",
  "VAR_FECHA_INICIO_COMISION": "",
  "VAR_FECHA_FIN_COMISION": "",
  "VAR_JEFE_DEPARTAMENTO_ACADEMICO": "",
  "VAR_FIRMA_DEPARTAMENTO_ACADEMICO": ""
}');
